export const one = () => 1
export const two = () => 2
export const three = () => 3
export const four = () => 4
export const five = () => 5
export const six = () => 6
export const seven = () => 7
export const eight = () => 8
export const nine = () => 9
export const PLUS = num => `+${num}`
export const MINUS = num => `-${num}`
export const DIVISION = num => `/${num}`
export const TIMES = num => `*${num}`
export const ONE = S => `1${S}`
export const TWO = S => `2${S}`
export const THREE = S => `3${S}`
export const FOUR = S => `4${S}`
export const FIVE = S => `5${S}`
export const SIX = S => `6${S}`
export const SEVEN = S => `7${S}`
export const EIGHT = S => `8${S}`
export const NINE = S => `9${S}`
